---
output: pdf_document
---

## NZP Bird Banding Project Volunteer Protocols

The following regulations are necessary to ensure that bird (and human!) safety is paramount and that we have a positive impact on zoo-goers and staff. Please be sure to read this document in full and ask your supervisor to clarify sections that you are unsure of.

*	Because most of our banding days will begin before the zoo opens, please arrive no earlier than 10 minutes before your shift. Contact Brian Evans (cell: 919-723-7907, office: 202-633-4298, email: EvansBr@si.edu) if you are running late. 
* We will not band during measurable precipitation events, during windy conditions (>4 on the Beaufort Scale, gusts of >19 miles per hour), or at temperatures below 0&deg;C. If the predicted weather conditions do not allow for banding, you will be informed via email that their shift for that day has been cancelled.
* You will need to complete zoonosis training prior to volunteering with banding operations.
* You cannot interact with the zoos collection birds on the day of trapping.
* The Bander's Code of Ethics will be followed at all times (see [this link](https://www.pwrc.usgs.gov/BBl/resources/ethics.cfm)).
* Please be sure to read the Mist Netter's Bird Safety Handbook, available at [this link](http://www.birdpop.org/docs/pubs/Smith_et_al_1997_Mist_Netters_Bird_Safety_Handbook.pdf).
*	Please do not bring guests with you while checking nets. Guests will be allowed at the banding station with prior approval of your supervisor.
*	Photos and media:
     *	Do not take pictures during your shift without the express permission of the project manager. Approval of pictures is on a per-picture basis and cannot include selfies. No picture taken shall be shared via social media (e.g., Facebook, Instagram).
     *	You may not use your cell phone during your shift except to contact your supervisor. During your shift you will carry a walkie-talkie with you to communicate with your supervisor and colleagues, however some areas may be outside of walkie-talkie range. 
*	Attire: 
    *	Uniforms: On duty volunteers are required wear name tags and uniforms. If you are unable to obtain a uniform we will provide a volunteer vest during your shift. 
    *	Footwear: There will be a lot of walking involved, so please be sure to wear appropriate footwear (i.e., sneakers or hiking boots). 
    *	Pants: Wear long, khaki pants. Cargo pants are ideal!
    * If you volunteer with the Bird House, you may not wear the same clothes during banding and Bird House shifts.
*	The locations where we will set up nets are predominantly not accessible to the public (i.e., staff areas). These areas should only be accessed during your shift. To ensure that our banding project does not interfere with other Zoo operations, please do not go into staff areas that aren’t pre-approved.
*	All permissions for handling wild birds pertain only to the banding activities at the National Zoo.
*	Please ask lots of questions and enjoy yourself! You will be learning a ton during this process and get to experience birds in a unique way. We look forward to working with you!


I have read and agree to the above protocol:  _____________________________________________  

Date: ____________________________________
